=== rixx/hk-split-maker/src/schema/splits.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://slaurbot.herokuapp.com/hk-split-maker/splits.schema.json",
    "title": "HK Splits",
    "description": "A Hollow Knight LiveSplit Configuration",
    "type": "object",
    "properties": {
        "ordered": {
            "description": "Ordered splits improve performance and are required for certain splits (e.g. KingsPass).",
            "type": "boolean"
        },
        "endTriggeringAutosplit": {
            "description": "Whether to end time at the last autosplit. Set this to false for full-game runs, where time ends on a final cutscene.",
            "type": "boolean"
        },
        "categoryName": {
            "description": "The category name on the associated speedrun.com board.",
            "type": "string"
        },
        "gameName": {
            "description": "The game name on the associated speedrun.com board.",
            "enum": [
                "Hollow Knight",
                "Hollow Knight Category Extensions",
                "Hollow Knight Mods"
            ]
        },
        "variables": {
            "description": "Additional optional info to describe your run",
            "type": "object",
            "properties": {
                "platform": {
                    "description": "Where you run the game.",
                    "enum": [
                        "PC",
                        "PlayStation 4",
                        "PlayStation 5",
                        "Switch",
                        "Xbox One",
                        "Xbox Series S",
                        "Xbox Series X"
                    ]
                },
                "patch": {
                    "description": "The version/build number of the version of the game you're playing.",
                    "enum": [
                        "1.0.0.5",
                        "1.0.0.6",
                        "1.0.0.7",
                        "1.0.1.1",
                        "1.0.1.4",
                        "1.0.2.8",
                        "1.0.3.1",
                        "1.0.3.4",
                        "1.0.3.7",
                        "1.1.1.4",
                        "1.1.1.6",
                        "1.1.1.7",
                        "1.1.1.8",
                        "1.2.1.0",
                        "1.2.1.1",
                        "1.2.1.4",
                        "1.2.2.1",
                        "1.3.1.5",
                        "1.4.1.4",
                        "1.4.2.4",
                        "1.4.3.2"
                    ]
                },
                "glitch": {
                    "description": "The glitch ruleset",
                    "enum": [
                        "No Major Glitches",
                        "Current Patch NMG",
                        "No Main Menu Storage",
                        "All Glitches"
                    ]
                }
            }
        },
        "splitIds": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "ordered",
        "endTriggeringAutosplit",
        "categoryName",
        "gameName",
        "splitIds"
    ]
}

=== rixx/hk-split-maker/src/asset/categories/fool.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "NotchShrumalOgres",
        "MantisClaw",
        "CycloneSlash",
        "ShamanStone",
        "GorgeousHusk",
        "DashSlash",
        "NailUpgrade1",
        "ShadeSoul",
        "SpellTwister",
        "LittleFool",
        "ColosseumBronze",
        "ColosseumSilver",
        "ColosseumGold"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Fool%",
    "variables": {
        "platform": "PC",
        "patch": "1.2.2.1",
        "glitch": "No Major Glitches"
    }
}

=== rixx/hk-split-maker/src/asset/categories/every.json
{
    "splitIds": [
        "AbyssShriek",
        "CrystalHeart",
        "CycloneSlash",
        "DashSlash",
        "DescendingDark",
        "DesolateDive",
        "DreamNail",
        "DreamNail2",
        "DreamGate",
        "GreatSlash",
        "HowlingWraiths",
        "IsmasTear",
        "MantisClaw",
        "MonarchWings",
        "MothwingCloak",
        "ShadeCloak",
        "ShadeSoul",
        "VengefulSpirit",
        "GodTuner",
        "HuntersMark",
        "KingsBrand",
        "LoveKey",
        "ElegantKey",
        "LumaflyLantern",
        "PaleLurkerKey",
        "PaleOre",
        "SalubrasBlessing",
        "SimpleKey",
        "SlyKey",
        "TramPass",
        "MaskFragment1",
        "MaskFragment2",
        "MaskFragment3",
        "Mask1",
        "MaskFragment5",
        "MaskFragment6",
        "MaskFragment7",
        "Mask2",
        "MaskFragment9",
        "MaskFragment10",
        "MaskFragment11",
        "Mask3",
        "MaskFragment13",
        "MaskFragment14",
        "MaskFragment15",
        "Mask4",
        "NailUpgrade1",
        "NailUpgrade2",
        "NailUpgrade3",
        "NailUpgrade4",
        "VesselFragment1",
        "VesselFragment2",
        "Vessel1",
        "VesselFragment4",
        "VesselFragment5",
        "Vessel2",
        "VesselFragment7",
        "VesselFragment8",
        "Vessel3",
        "BrokenVessel",
        "BroodingMawlek",
        "Collector",
        "CrystalGuardian1",
        "CrystalGuardian2",
        "DungDefender",
        "ElderHu",
        "FalseKnight",
        "FailedKnight",
        "Flukemarm",
        "Galien",
        "GodTamer",
        "Gorb",
        "GreyPrince",
        "GruzMother",
        "HollowKnightBoss",
        "Hornet1",
        "Hornet2",
        "LostKin",
        "MantisLords",
        "Markoth",
        "Marmu",
        "MegaMossCharger",
        "NightmareKingGrimm",
        "NoEyes",
        "Nosk",
        "MatoOroNailBros",
        "RadianceBoss",
        "PureVessel",
        "SheoPaintmaster",
        "SlyNailsage",
        "SoulMaster",
        "SoulTyrant",
        "TraitorLord",
        "TroupeMasterGrimm",
        "Uumuu",
        "BlackKnight",
        "WhiteDefender",
        "Xero",
        "HiveKnight",
        "VengeflyKingP",
        "GruzMotherP",
        "FalseKnightP",
        "MassiveMossChargerP",
        "Hornet1P",
        "GorbP",
        "DungDefenderP",
        "SoulWarriorP",
        "BroodingMawlekP",
        "OroMatoNailBrosP",
        "XeroP",
        "CrystalGuardianP",
        "SoulMasterP",
        "OblobblesP",
        "MantisLordsP",
        "MarmuP",
        "NoskP",
        "FlukemarmP",
        "BrokenVesselP",
        "SheoPaintmasterP",
        "HiveKnightP",
        "ElderHuP",
        "CollectorP",
        "GodTamerP",
        "TroupeMasterGrimmP",
        "GalienP",
        "GreyPrinceZoteP",
        "UumuuP",
        "Hornet2P",
        "SlyP",
        "EnragedGuardianP",
        "LostKinP",
        "NoEyesP",
        "TraitorLordP",
        "WhiteDefenderP",
        "FailedChampionP",
        "MarkothP",
        "WatcherKnightsP",
        "SoulTyrantP",
        "PureVesselP",
        "NoskHornetP",
        "NightmareKingGrimmP",
        "Hegemol",
        "Lurien",
        "Monomon",
        "Dreamer1",
        "Dreamer2",
        "Dreamer3",
        "NightmareLantern",
        "NightmareLanternDestroyed",
        "SeerDeparts",
        "SpiritGladeOpen",
        "WatcherChandelier",
        "CityGateOpen",
        "BeastsDenTrapBench",
        "UnchainedHollowKnight",
        "HollowKnightDreamnail",
        "ColosseumBronze",
        "ColosseumSilver",
        "ColosseumGold",
        "Pantheon1",
        "Pantheon2",
        "Pantheon3",
        "Pantheon4",
        "Pantheon5",
        "PathOfPain",
        "AspidHunter",
        "Aluba",
        "HuskMiner",
        "GreatHopper",
        "GorgeousHusk",
        "MenderBug",
        "MossKnight",
        "MushroomBrawler",
        "Zote1",
        "Zote2",
        "ZoteKilled",
        "CrossroadsStation",
        "GreenpathStation",
        "QueensStationStation",
        "QueensGardensStation",
        "StoreroomsStation",
        "KingsStationStation",
        "RestingGroundsStation",
        "DeepnestStation",
        "HiddenStationStation",
        "StagnestStation",
        "MrMushroom1",
        "MrMushroom2",
        "MrMushroom3",
        "MrMushroom4",
        "MrMushroom5",
        "MrMushroom6",
        "MrMushroom7",
        "Abyss",
        "CityOfTears",
        "Colosseum",
        "CrystalPeak",
        "Deepnest",
        "DeepnestSpa",
        "Dirtmouth",
        "FogCanyon",
        "ForgottenCrossroads",
        "FungalWastes",
        "Godhome",
        "Greenpath",
        "Hive",
        "InfectedCrossroads",
        "KingdomsEdge",
        "QueensGardens",
        "RestingGrounds",
        "RoyalWaterways",
        "TeachersArchive",
        "WhitePalace",
        "WhitePalaceSecretRoom",
        "KingsPass",
        "BlueLake",
        "BaldurShell",
        "Dashmaster",
        "DeepFocus",
        "DefendersCrest",
        "Dreamshield",
        "DreamWielder",
        "Flukenest",
        "FragileGreed",
        "FragileHeart",
        "FragileStrength",
        "FuryOfTheFallen",
        "GatheringSwarm",
        "GlowingWomb",
        "Grimmchild",
        "Grimmchild2",
        "Grimmchild3",
        "Grimmchild4",
        "GrubberflysElegy",
        "Grubsong",
        "HeavyBlow",
        "Hiveblood",
        "JonisBlessing",
        "WhiteFragmentLeft",
        "WhiteFragmentRight",
        "Kingsoul",
        "LifebloodCore",
        "LifebloodHeart",
        "Longnail",
        "MarkOfPride",
        "NailmastersGlory",
        "QuickFocus",
        "QuickSlash",
        "ShamanStone",
        "ShapeOfUnn",
        "SharpShadow",
        "SoulCatcher",
        "SoulEater",
        "SpellTwister",
        "SporeShroom",
        "Sprintmaster",
        "StalwartShell",
        "SteadyBody",
        "ThornsOfAgony",
        "VoidHeart",
        "WaywardCompass",
        "Weaversong",
        "NotchShrumalOgres",
        "NotchFogCanyon",
        "NotchSalubra1",
        "NotchSalubra2",
        "NotchSalubra3",
        "NotchSalubra4",
        "Lemm1",
        "Lemm2",
        "ElderbugFlower",
        "BrettaRescued",
        "BrummFlame",
        "LittleFool",
        "Flame1",
        "Flame2",
        "Flame3",
        "Ore1",
        "Ore2",
        "Ore3",
        "Ore4",
        "Ore5",
        "Ore6",
        "Grub1",
        "Grub2",
        "Grub3",
        "Grub4",
        "Grub5",
        "Grub6",
        "Grub7",
        "Grub8",
        "Grub9",
        "Grub10",
        "Grub11",
        "Grub12",
        "Grub13",
        "Grub14",
        "Grub15",
        "Grub16",
        "Grub17",
        "Grub18",
        "Grub19",
        "Grub20",
        "Grub21",
        "Grub22",
        "Grub23",
        "Grub24",
        "Grub25",
        "Grub26",
        "Grub27",
        "Grub28",
        "Grub29",
        "Grub30",
        "Grub31",
        "Grub32",
        "Grub33",
        "Grub34",
        "Grub35",
        "Grub36",
        "Grub37",
        "Grub38",
        "Grub39",
        "Grub40",
        "Grub41",
        "Grub42",
        "Grub43",
        "Grub44",
        "Grub45",
        "Grub46",
        "TreeMound",
        "TreeCity",
        "TreePeak",
        "TreeDeepnest",
        "TreeCrossroads",
        "TreeLegEater",
        "TreeMantisVillage",
        "TreeGreenpath",
        "TreeHive",
        "TreeCliffs",
        "TreeKingdomsEdge",
        "TreeQueensGardens",
        "TreeRestingGrounds",
        "TreeWaterways",
        "TreeGlade",
        "TollBenchQG",
        "TollBenchCity",
        "TollBenchBasin",
        "WhitePalaceOrb1",
        "WhitePalaceOrb2",
        "WhitePalaceOrb3"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "foo%",
    "variables": {
        "platform": "PC",
        "patch": "1.2.2.1"
    }
}

=== rixx/hk-split-maker/src/asset/categories/allunbreakablecharms_steel_soul.json
{
    "splitIds": [
        "VengefulSpirit",
        "MothwingCloak",
        "MegaMossCharger",
        "MantisClaw",
        "MantisLords",
        "FragileStrength",
        "DesolateDive",
        "ShamanStone",
        "CrystalGuardian1",
        "CrystalHeart",
        "DreamNail",
        "Xero",
        "Gorb",
        "KingdomsEdge",
        "KingsStationStation",
        "GorgeousHusk",
        "BlackKnight",
        "Lemm2"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "All Unbreakable Charms",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/enragedguardian.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "MantisClaw",
        "GruzMother",
        "GorgeousHusk",
        "LumaflyLantern",
        "CrystalGuardian1",
        "CrystalGuardian2"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Enraged Guardian%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/worldsoul.json
{
    "splitIds": [
        "FalseKnight",
        "VengefulSpirit",
        "MothwingCloak",
        "MantisClaw",
        "QueensStationStation",
        "VesselFragment1",
        "VesselFragment2",
        "ShamanStone",
        "DreamNail",
        "Vessel1",
        "KingsStationStation",
        "GorgeousHusk",
        "DashSlash",
        "DesolateDive",
        "SoulTyrant",
        "VesselFragment4",
        "CrystalHeart",
        "SpiritGladeOpen",
        "Lemm2",
        "VesselFragment5",
        "BrokenVessel",
        "LostKin",
        "Vessel2",
        "VesselFragment8",
        "Vessel3"
    ],
    "ordered": false,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Worldsoul",
    "variables": {
        "platform": "PC",
        "patch": "1.2.2.1",
        "glitch": "No Major Glitches"
    }
}

=== rixx/hk-split-maker/src/asset/categories/elderbug.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "MantisClaw",
        "BlueLake",
        "DreamNail",
        "DesolateDive",
        "StoreroomsStation",
        "ElderbugFlower"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Elderbug%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "No Major Glitches"
    }
}

=== rixx/hk-split-maker/src/asset/categories/spelless.json
{
    "splitIds": [
        "FuryOfTheFallen",
        "FalseKnight",
        "Longnail",
        "Greenpath",
        "MothwingCloak",
        "MegaMossCharger",
        "FragileStrength",
        "MantisClaw",
        "DreamNail",
        "GorgeousHusk",
        "NailUpgrade1",
        "BlackKnight",
        "LumaflyLantern",
        "CrystalHeart",
        "SporeShroom",
        "BeastsDenTrapBench",
        "Hegemol"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Spelless",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "No Major Glitches"
    }
}

=== rixx/hk-split-maker/src/asset/categories/all-skills.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "MantisClaw",
        "BlueLake",
        "GorgeousHusk",
        "DashSlash",
        "ShadeSoul",
        "DesolateDive",
        "KingsStationStation",
        "CrystalHeart",
        "DescendingDark",
        "DreamNail",
        "Lurien",
        "Abyss",
        "MonarchWings",
        "KingsBrand",
        "CycloneSlash",
        "Monomon",
        "GreatSlash",
        "HowlingWraiths",
        "Hegemol",
        "ShadeCloak",
        "AbyssShriek",
        "UnchainedHollowKnight"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight",
    "categoryName": "All Skills",
    "variables": {
        "platform": "PC",
        "patch": "1.2.2.1"
    }
}
