=== rixx/hk-split-maker/src/schema/splits.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://slaurbot.herokuapp.com/hk-split-maker/splits.schema.json",
    "title": "HK Splits",
    "description": "A Hollow Knight LiveSplit Configuration",
    "type": "object",
    "properties": {
        "ordered": {
            "description": "Ordered splits improve performance and are required for certain splits (e.g. KingsPass).",
            "type": "boolean"
        },
        "endTriggeringAutosplit": {
            "description": "Whether to end time at the last autosplit. Set this to false for full-game runs, where time ends on a final cutscene.",
            "type": "boolean"
        },
        "categoryName": {
            "description": "The category name on the associated speedrun.com board.",
            "type": "string"
        },
        "gameName": {
            "description": "The game name on the associated speedrun.com board.",
            "enum": [
                "Hollow Knight",
                "Hollow Knight Category Extensions",
                "Hollow Knight Mods"
            ]
        },
        "variables": {
            "description": "Additional optional info to describe your run",
            "type": "object",
            "properties": {
                "platform": {
                    "description": "Where you run the game.",
                    "enum": [
                        "PC",
                        "PlayStation 4",
                        "PlayStation 5",
                        "Switch",
                        "Xbox One",
                        "Xbox Series S",
                        "Xbox Series X"
                    ]
                },
                "patch": {
                    "description": "The version/build number of the version of the game you're playing.",
                    "enum": [
                        "1.0.0.5",
                        "1.0.0.6",
                        "1.0.0.7",
                        "1.0.1.1",
                        "1.0.1.4",
                        "1.0.2.8",
                        "1.0.3.1",
                        "1.0.3.4",
                        "1.0.3.7",
                        "1.1.1.4",
                        "1.1.1.6",
                        "1.1.1.7",
                        "1.1.1.8",
                        "1.2.1.0",
                        "1.2.1.1",
                        "1.2.1.4",
                        "1.2.2.1",
                        "1.3.1.5",
                        "1.4.1.4",
                        "1.4.2.4",
                        "1.4.3.2"
                    ]
                },
                "glitch": {
                    "description": "The glitch ruleset",
                    "enum": [
                        "No Major Glitches",
                        "Current Patch NMG",
                        "No Main Menu Storage",
                        "All Glitches"
                    ]
                }
            }
        },
        "splitIds": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "ordered",
        "endTriggeringAutosplit",
        "categoryName",
        "gameName",
        "splitIds"
    ]
}

=== rixx/hk-split-maker/src/asset/categories/112-apb.json
{
    "splitIds": [
        "FuryOfTheFallen",
        "VengefulSpirit",
        "Greenpath",
        "Zote1",
        "MothwingCloak",
        "NotchShrumalOgres",
        "MantisClaw",
        "Grub1",
        "CityOfTears",
        "Lemm2",
        "SpellTwister",
        "DesolateDive",
        "Grub2",
        "SimpleKey",
        "Grub3",
        "Grub4",
        "CrystalPeak",
        "Grub5",
        "SlyKey",
        "CrystalHeart",
        "Grub6",
        "Grub7",
        "Grub8",
        "Grub9",
        "DescendingDark",
        "DreamNail",
        "Dreamshield",
        "Grub10",
        "ShamanStone",
        "ElegantKey",
        "ShadeSoul",
        "Grub11",
        "DungDefender",
        "Grub12",
        "IsmasTear",
        "MonarchWings",
        "LostKin",
        "Grub13",
        "GlowingWomb",
        "FailedKnight",
        "CycloneSlash",
        "VesselFragment1",
        "JonisBlessing",
        "Grimmchild",
        "Xero",
        "DreamGate",
        "Grub14",
        "DeepFocus",
        "CrystalGuardian2",
        "Grub15",
        "LumaflyLantern",
        "Vessel1",
        "GreatSlash",
        "ThornsOfAgony",
        "Grub16",
        "Grub17",
        "MegaMossCharger",
        "Grub18",
        "VesselFragment4",
        "HowlingWraiths",
        "NoEyes",
        "MaskFragment3",
        "Grimmchild2",
        "Grub19",
        "SoulEater",
        "VesselFragment5",
        "KingdomsEdge",
        "KingsBrand",
        "AbyssShriek",
        "ShadeCloak",
        "Grub20",
        "Mask1",
        "BrettaRescued",
        "MantisLords",
        "MaskFragment5",
        "TroupeMasterGrimm",
        "Grub21",
        "BroodingMawlek",
        "Grub22",
        "FragileStrength",
        "ElderHu",
        "Grub23",
        "Uumuu",
        "MaskFragment7",
        "QueensGardens",
        "LoveKey",
        "Grub24",
        "SporeShroom",
        "Grub25",
        "Grub26",
        "Grub27",
        "Marmu",
        "Grub28",
        "TraitorLord",
        "Hegemol",
        "Grub29",
        "Grub30",
        "Weaversong",
        "Galien",
        "TramPass",
        "Zote2",
        "Grub31",
        "Grub32",
        "Nosk",
        "SharpShadow",
        "Vessel2",
        "Grub33",
        "Hive",
        "Grub34",
        "Mask2",
        "Hiveblood",
        "Grub35",
        "Grub36",
        "Grub37",
        "Markoth",
        "DashSlash",
        "Grub38",
        "QuickSlash",
        "Collector",
        "Grub41",
        "Grub42",
        "Grub43",
        "Grub44",
        "BlackKnight",
        "NailUpgrade3",
        "WhiteDefender",
        "LittleFool",
        "ColosseumBronze",
        "ColosseumSilver",
        "ColosseumGold",
        "Grub45",
        "BaldurShell",
        "Grub46",
        "NightmareLanternDestroyed",
        "ShapeOfUnn",
        "GreyPrince",
        "Sprintmaster",
        "DreamNail2",
        "NotchSalubra3",
        "MaskFragment15",
        "Mask4",
        "Kingsoul",
        "Vessel3",
        "LifebloodCore",
        "VoidHeart",
        "NailUpgrade4",
        "Flukemarm",
        "GodTuner",
        "GorbP",
        "OroMatoNailBrosP",
        "MarmuP",
        "SheoPaintmasterP",
        "GalienP",
        "SlyP",
        "FailedChampionP",
        "PureVesselP",
        "XeroP",
        "MarmuP",
        "HiveKnightP",
        "WatcherKnightsP",
        "EnragedGuardianP",
        "SoulTyrantP",
        "PureVesselP"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight",
    "categoryName": "112% APB",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2"
    }
}

=== rixx/hk-split-maker/src/asset/categories/allstagstations.json
{
    "splitIds": [
        "CrossroadsStation",
        "VengefulSpirit",
        "GreenpathStation",
        "MothwingCloak",
        "MantisClaw",
        "QueensStationStation",
        "GruzMother",
        "DreamNail",
        "GorgeousHusk",
        "Lemm2",
        "StoreroomsStation",
        "TollBenchBasin",
        "DeepnestSpa",
        "DeepnestStation",
        "QueensGardens",
        "QueensGardensStation",
        "StagnestStation"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "All Stag Stations",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "No Major Glitches"
    }
}

=== rixx/hk-split-maker/src/asset/categories/allunbreakablecharms.json
{
    "splitIds": [
        "VengefulSpirit",
        "MothwingCloak",
        "MantisClaw",
        "MantisLords",
        "GruzMother",
        "DreamNail",
        "FragileStrength",
        "Gorb",
        "Xero",
        "KingdomsEdge",
        "KingsStationStation",
        "GorgeousHusk",
        "BlackKnight",
        "Lemm2"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "All Unbreakable Charms",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/mrmushroomending.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "MantisClaw",
        "BlueLake",
        "DreamNail",
        "BlackKnight",
        "LumaflyLantern",
        "CrystalHeart",
        "Uumuu",
        "SporeShroom",
        "Hegemol",
        "MrMushroom1",
        "MrMushroom7"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Mr. Mushroom Ending",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "No Major Glitches"
    }
}

=== rixx/hk-split-maker/src/asset/categories/aluba.json
{
    "splitIds": [
        "KingsPass",
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "Aluba"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Aluba%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/4MS.json
{
    "splitIds": [
        "Dirtmouth",
        "Grub1",
        "MaskFragment1",
        "Grub2",
        "AspidHunter",
        "MaskFragment2",
        "GruzMother",
        "Grub3",
        "Grub4",
        "Grub5",
        "MaskFragment3",
        "Mask1"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "4 Mask Shards",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/lowAB.json
{
    "splitIds": [
        "GruzMother",
        "DreamNail",
        "MantisClaw",
        "Hegemol",
        "BlackKnight",
        "Lurien",
        "CrystalHeart",
        "Uumuu",
        "Monomon"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight Mods",
    "categoryName": "Low% All Bindings",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/nosk.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "MantisClaw",
        "DeepnestSpa",
        "Nosk"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Nosk%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}
