=== rixx/hk-split-maker/src/schema/splits.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://slaurbot.herokuapp.com/hk-split-maker/splits.schema.json",
    "title": "HK Splits",
    "description": "A Hollow Knight LiveSplit Configuration",
    "type": "object",
    "properties": {
        "ordered": {
            "description": "Ordered splits improve performance and are required for certain splits (e.g. KingsPass).",
            "type": "boolean"
        },
        "endTriggeringAutosplit": {
            "description": "Whether to end time at the last autosplit. Set this to false for full-game runs, where time ends on a final cutscene.",
            "type": "boolean"
        },
        "categoryName": {
            "description": "The category name on the associated speedrun.com board.",
            "type": "string"
        },
        "gameName": {
            "description": "The game name on the associated speedrun.com board.",
            "enum": [
                "Hollow Knight",
                "Hollow Knight Category Extensions",
                "Hollow Knight Mods"
            ]
        },
        "variables": {
            "description": "Additional optional info to describe your run",
            "type": "object",
            "properties": {
                "platform": {
                    "description": "Where you run the game.",
                    "enum": [
                        "PC",
                        "PlayStation 4",
                        "PlayStation 5",
                        "Switch",
                        "Xbox One",
                        "Xbox Series S",
                        "Xbox Series X"
                    ]
                },
                "patch": {
                    "description": "The version/build number of the version of the game you're playing.",
                    "enum": [
                        "1.0.0.5",
                        "1.0.0.6",
                        "1.0.0.7",
                        "1.0.1.1",
                        "1.0.1.4",
                        "1.0.2.8",
                        "1.0.3.1",
                        "1.0.3.4",
                        "1.0.3.7",
                        "1.1.1.4",
                        "1.1.1.6",
                        "1.1.1.7",
                        "1.1.1.8",
                        "1.2.1.0",
                        "1.2.1.1",
                        "1.2.1.4",
                        "1.2.2.1",
                        "1.3.1.5",
                        "1.4.1.4",
                        "1.4.2.4",
                        "1.4.3.2"
                    ]
                },
                "glitch": {
                    "description": "The glitch ruleset",
                    "enum": [
                        "No Major Glitches",
                        "Current Patch NMG",
                        "No Main Menu Storage",
                        "All Glitches"
                    ]
                }
            }
        },
        "splitIds": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "ordered",
        "endTriggeringAutosplit",
        "categoryName",
        "gameName",
        "splitIds"
    ]
}

=== rixx/hk-split-maker/src/asset/categories/gpz.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "Zote1",
        "MothwingCloak",
        "ShamanStone",
        "MantisClaw",
        "BrettaRescued",
        "DeepnestSpa",
        "Zote2",
        "TramPass",
        "NailUpgrade1",
        "MonarchWings",
        "LittleFool",
        "ZoteKilled",
        "DreamNail",
        "GreyPrince"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "GPZ%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/allcharmnotches.json
{
    "splitIds": [
        "FuryOfTheFallen",
        "VengefulSpirit",
        "SoulCatcher",
        "Greenpath",
        "MothwingCloak",
        "NotchShrumalOgres",
        "Dashmaster",
        "MantisClaw",
        "Lemm2",
        "SpellTwister",
        "DesolateDive",
        "SlyKey",
        "CrystalHeart",
        "DeepFocus",
        "NotchSalubra1",
        "DreamNail",
        "Dreamshield",
        "BaldurShell",
        "NightmareLantern",
        "ElegantKey",
        "Grimmchild",
        "NotchFogCanyon",
        "ShadeSoul",
        "ThornsOfAgony",
        "Grimmchild2",
        "SoulEater",
        "LittleFool",
        "ColosseumBronze",
        "TroupeMasterGrimm",
        "WaywardCompass",
        "GlowingWomb",
        "FragileStrength",
        "SporeShroom",
        "QuickFocus",
        "NotchSalubra4"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "All Charm Notches",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "No Major Glitches"
    }
}

=== rixx/hk-split-maker/src/asset/categories/eatmetoo.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Eat Me Too",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/al2ba.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "Aluba",
        "MantisClaw",
        "DeepnestSpa",
        "QueensGardens"
    ],
    "ordered": true,
    "endTriggeringAutosplit": false,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Al2ba%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/shriek.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "MantisClaw",
        "HowlingWraiths",
        "BlueLake",
        "KingsBrand",
        "AbyssShriek"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Shriek%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/NMG.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "MantisClaw",
        "GorgeousHusk",
        "DashSlash",
        "GreatSlash",
        "CycloneSlash",
        "NailmastersGlory"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "NMG%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}

=== rixx/hk-split-maker/src/asset/categories/zote.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "Zote1",
        "MothwingCloak",
        "MantisClaw",
        "Zote2",
        "TramPass",
        "LittleFool",
        "ZoteKilled"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Zote%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "No Major Glitches"
    }
}

=== rixx/hk-split-maker/src/asset/categories/marmu.json
{
    "splitIds": [
        "VengefulSpirit",
        "Greenpath",
        "MothwingCloak",
        "MantisClaw",
        "DeepnestSpa",
        "QueensGardens",
        "QueensGardensStation",
        "DreamNail",
        "Marmu"
    ],
    "ordered": true,
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "categoryName": "Marmu%",
    "variables": {
        "platform": "PC",
        "patch": "1.4.3.2",
        "glitch": "Current Patch NMG"
    }
}
